name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        brew install exiftool libraw
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # 최신 버전으로 업데이트하여 심볼릭 링크 버그 수정
        pip install --upgrade pyinstaller
        pip install --upgrade PySide6
        pip install exifread
    
    - name: Clean previous build artifacts
      run: |
        rm -rf dist
        rm -rf build
        rm -rf __pycache__
        rm -rf *.spec
        # PySide6 캐시 및 임시 파일도 정리
        rm -rf ~/.cache/pip
        find . -name "*.pyc" -delete
        find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
    
    - name: Build macOS app
      run: |
        chmod +x build_mac_app.sh
        ./build_mac_app.sh
    
    - name: Retry build if failed (cleanup and retry)
      if: failure()
      run: |
        echo "빌드 실패 - 추가 정리 후 재시도"
        rm -rf dist build *.spec
        find . -path "*/PySide6/Qt/lib/Qt3DAnimation.framework/Resources" -type l -delete 2>/dev/null || true
        find . -path "*/PySide6/Qt/lib/*/Resources" -type l -delete 2>/dev/null || true
        chmod +x build_mac_app.sh
        ./build_mac_app.sh
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VibeCulling-macOS
        path: dist/