name: Build macOS App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install system dependencies
      run: |
        brew install exiftool libraw
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # 최신 버전으로 업데이트하여 심볼릭 링크 버그 수정
        pip install --upgrade pyinstaller
        pip install --upgrade PySide6
        pip install exifread
    
    - name: Clean previous build artifacts (강력한 정리)
      run: |
        # 모든 빌드 관련 파일 완전 삭제
        sudo rm -rf dist build __pycache__ *.spec 2>/dev/null || true
        # PySide6 관련 모든 캐시 정리
        sudo rm -rf ~/.cache/pip ~/.cache/pyinstaller 2>/dev/null || true
        sudo rm -rf /tmp/pip-* /tmp/_MEI* 2>/dev/null || true
        # Python 캐시 파일 모두 삭제
        find . -name "*.pyc" -delete 2>/dev/null || true
        find . -name "__pycache__" -type d -exec sudo rm -rf {} + 2>/dev/null || true
        # 기존 심볼릭 링크 강제 삭제
        find . -type l -delete 2>/dev/null || true
        # 작업 디렉토리 새로 생성
        mkdir -p dist build
        # spec 파일 강제 삭제 (매번 새로 생성하도록)
        rm -f VibeCulling.spec 2>/dev/null || true
    
    - name: Build macOS app
      run: |
        chmod +x build_mac_app.sh
        ./build_mac_app.sh
        # 빌드 후 spec 파일 삭제 (심볼릭 링크 충돌 방지)
        rm -f VibeCulling.spec 2>/dev/null || true
    
    - name: Retry build if failed (강력한 정리 후 재시도)
      if: failure()
      run: |
        echo "빌드 실패 - 강력한 정리 후 재시도"
        # 모든 빌드 관련 파일 완전 삭제
        sudo rm -rf dist build *.spec __pycache__ .pytest_cache 2>/dev/null || true
        # 모든 캐시 완전 정리
        sudo rm -rf ~/.cache/pip ~/.cache/pyinstaller 2>/dev/null || true
        sudo rm -rf /tmp/pip-* /tmp/_MEI* /tmp/pyinstaller* 2>/dev/null || true
        # 모든 심볼릭 링크 삭제
        find . -type l -delete 2>/dev/null || true
        find . -name "*.pyc" -delete 2>/dev/null || true
        # 작업 디렉토리 새로 생성
        mkdir -p dist build
        # 재시도
         chmod +x build_mac_app.sh
         ./build_mac_app.sh
         # 재시도 후에도 spec 파일 삭제
         rm -f VibeCulling.spec 2>/dev/null || true
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: VibeCulling-macOS
        path: dist/